### ISSUE TITLE
Support for reviews

### ISSUE THREAD

**Issue by afirlejczyk** [DivanteLtd/magento2-vsbridge-indexer#1]
Add new indexer for exporting reviews to ES

**Comment by pkarw** [comment]
Is this one still valid issue? I remember there was a question on if we should assign reviews to `product.configurable_children.id` or to `product.id` (probably to configurable children).

**Comment by afirlejczyk** [comment]
Yes, it is a valid issue, I still didn't implement exporting reviews to elastic.

No -> Magento is assigning reviews to configurable product.

**Comment by afirlejczyk** [comment]
Added in https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/38
