### ISSUE TITLE
magento2-vsbridge-indexer need to update the Reviews sync?

### ISSUE THREAD

**Issue by wubuyun** [DivanteLtd/magento2-vsbridge-indexer#103]
You should be aware that Reviews are stored in the Elasticsearch. To display Reviews correctly, you need to update your mage2vuestorefront

and run the Reviews sync:

node --harmony cli.js reviews

**Comment by afirlejczyk** [comment]
mage2vuestorefront is a separate tool.

This module allows you to export reviews to ES using a new indexer.
`php bin/magento indexer:reindex vsbridge_review_indexer`

**Comment by afirlejczyk** [comment]
I will update readme later #104
