### ISSUE TITLE
Customizing child product attributes

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/magento2-vsbridge-indexer#105]
It would be nice if we could somehow customize indexed attributes. E.g. I would like to fetch configurable_children.media_gallery.

**Comment by Fifciu** [comment]
I figured out we can do it here: https://github.com/DivanteLtd/magento2-vsbridge-indexer/blob/develop/src/module-vsbridge-indexer-catalog/Model/Attributes/ConfigurableAttributes.php

However, it would be nice, if we could set it in Magento's admin panel

**Comment by afirlejczyk** [comment]
Added with #185
