### ISSUE TITLE
Vue Storefont Menu is not updated with categories

### ISSUE THREAD

**Issue by kumarnaveenpal** [DivanteLtd/magento2-vsbridge-indexer#116]
Hi There ,

I have imported the all the product on making a change in **'vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-catalog/Model/Indexer/DataProvider/Product/AttributeData.php'** file.
**Old code:**
if ( $this->settings->useMagentoUrlKeys() ) {
$productData['slug'] = $productData['url_key'];
}
**Changed code:**
if ( $this->settings->useMagentoUrlKeys() && isset($productData['url_key']) ) {
$productData['slug'] = $productData['url_key'];
}

>> It was showing error of undefined key 'url_key'. The reason may be some products in my store which does not has URL Key set.

All indexes re-indexed successfully, Now I noticed that the menu of storefront is still showing sample data (old) categories, The categories of my store is not updated there.
When I search for any product then it is showing the product.

![image](https://user-images.githubusercontent.com/9878310/64852883-dfee6a00-d637-11e9-866c-b6551b86178c.png)

Please guide me how to update the menu with the updated products categories?
is there something missing in configuration?

Edit:
As I was trying to fix this, I deleted the **vue_storefront_catalog** index (As I am not using this index for my site) and rebuid and restored the database, now, old categories are not visible and it is adding the category to the menu, but it is adding the only categories which are viewed by the user and visible only to that particular user.
Please guide how can I solve this issue? 

Thanks!

**Comment by philippsander** [comment]
This still seems to be an issue. I can not find categories in my ES.
I only find the products.

**Comment by kumarnaveenpal** [comment]
I solved this my own, actually it was needed to restart vue-storfront app.
