### ISSUE TITLE
Feature request: re-index subcategories when parent category changes

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/magento2-vsbridge-indexer#122]
##Feature request

When a category is modified (like `url_key`) the indexer should perform re-index on subcategories attached with this category.
see [DivanteLtd/vue-storefront#3622](https://github.com/DivanteLtd/vue-storefront/issues/3622)

**Comment by afirlejczyk** [comment]
@pkarw @underf

`product.url_path` - does not include parent category path (by default), so there is no need to update product after category changed.
we only have "short" url_path for products (by default)

I can check after we change parent category url_key, if url_path for subcategories is updated - I understand there were a problem ? 
Like url path for parent category was updated but not for a subcategories, right ?

**Comment by afirlejczyk** [comment]
If url_key has change for category, all subcategories will be re-index automatically. 

Fix in develop branch. 
https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/128
