### ISSUE TITLE
First Indexing throws error

### ISSUE THREAD

**Issue by philippsander** [DivanteLtd/magento2-vsbridge-indexer#124]
`Vsbridge Product Indexer indexer process unknown error:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [my_store_5] as the final mapping would have more than 1 type: [product, category]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [my_store_5] as the final mapping would have more than 1 type: [product, category]"},"status":400}`

**Comment by pkarw** [comment]
Elastic6+ support is in the making -
Expected in November. Please try out Roastic 5.6 instead

**Comment by philippsander** [comment]
Thank you for the information!
