### ISSUE TITLE
Notice: Undefined index: stock on indexing

### ISSUE THREAD

**Issue by ProxiBlue** [DivanteLtd/magento2-vsbridge-indexer#132]
Hello,

Clean install of magento 2.3.3 with sample data (all via composer)
Installed this.

Get this:

```05:35 $ ./bin/magento vsbridge:reindex --all
Reindexing all stores...
Reindexing store Default Store View...
Vsbridge Product Indexer indexer process unknown error:
Notice: Undefined index: stock in /vagrant/sites/magento2/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-catalog/Model/Indexer/DataProvider/Product/ConfigurableData.php on line 284
Vsbridge Category Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Attributes Indexer index has been rebuilt successfully in 00:00:01
Vsbridge Product Category Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Cms Block Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Cms Page Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Review Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Tax Rule Indexer index has been rebuilt successfully in 00:00:00
All stores have been reindexed!
```

**Comment by afirlejczyk** [comment]
Hello @ProxiBlue 
Which version of magento2-vsbridge-indexer did you installed ? 
Did you also installed divante/magento2-vsbridge-indexer-msi ? 

I guess configurable product does not have stock data.. 
did you reindex Magento inventory indexer first ? 

Let me know, I will check if I can reproduce error.

**Comment by afirlejczyk** [comment]
I check indexing on clean Magento with sample data and it works (without msi support). 
Please try to reindex inventory just in case: 
`php bin/magento indexer:reindex cataloginventory_stock`

**Comment by ProxiBlue** [comment]
@afirlejczyk 

Thank you for looking to reproduce.
In light of your finding, I tore down all setup or magento2, and started from scratch.

Issue can no longer be reproduced.

13:20 $ php bin/magento indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:01
Product EAV index has been rebuilt successfully in 00:00:01
Stock index has been rebuilt successfully in 00:00:01
Inventory index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:01
Google Product Removal Feed index has been rebuilt successfully in 00:00:00
Google Product Feed index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:03
Vsbridge Product Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Category Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Attributes Indexer index has been rebuilt successfully in 00:00:01
Vsbridge Cms Block Indexer index has been rebuilt successfully in 00:00:07
Vsbridge Cms Page Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Review Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Tax Rule Indexer index has been rebuilt successfully in 00:00:00
✔ /vagrant/sites/magento2 [master|✚ 2]
