### ISSUE TITLE
category product_count wrong values

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/magento2-vsbridge-indexer#133]
`product_count` shows some definitely wrong values.

I am on https://demo.vuestorefront.io, looking at network calls to ES when browsing categories via side menu.

"Men/Tops"
![image](https://user-images.githubusercontent.com/8209966/66927207-b60dd600-f02f-11e9-818b-adfb2543ccef.png)
0 products can't be right, it should be the sum of the subcategories products.

"Men/Tops/Jackets"
![image](https://user-images.githubusercontent.com/8209966/66927304-dc337600-f02f-11e9-805e-fc2c876d89ef.png)
176 products isn't right either, on page it shows 11 items

![image](https://user-images.githubusercontent.com/8209966/66927515-39c7c280-f030-11e9-8479-2e1d4bfd8caf.png)

Same applies to "Women", but not to "Gear" and "Training", which have one level nesting less, not sure if that would make a difference.

**Comment by pkarw** [comment]
@afirlejczyk that's right - it's just the number of products directly attached to any specific category and VSF is doing a nested query to get all the products directyl attached and from subcategories as well

**Comment by undefinederror** [comment]
Sorry for the delay in getting back. Thank you for your answers.

I understand those values are taken straight from ES. I used https://demo.vuestorefront.io/ as a common ground for the example but I get exactly the same on a local magento install with sample products.

I understand (only now :)) that the 176 in Men/Tops/Jackets is the sum of all the *simple* products, which is different than the 11 *items* shown on page. So the 176 does make sense.
What doesn't make sense is the *0* in Men/Tops (and all other similar categories), which as far as I can tell is just plainly incorrect.

I guess it depends on how the value gets used.

**Comment by afirlejczyk** [comment]
> I opened the issue here because I thought that magento2-vsbridge-indexer was responsible for counting up the products from mysql and writing to ES.

It is, but VSF demo doesn't use this extension :) it is using https://github.com/DivanteLtd/mage2vuestorefront 
- so it get data directly from magento api, I don't know why Magento API return 0 for this category.

So I would report issue to: https://github.com/DivanteLtd/mage2vuestorefront or to https://github.com/DivanteLtd/vue-storefront ;)

**Comment by undefinederror** [comment]
Thank you @afirlejczyk 
Yes you are right, those zeros come straight from magento api. To think that it can't event count right..

Apparently all it takes to teach it how to count is flagging categories as "anchors"
https://magento.stackexchange.com/questions/24429/magento-category-product-count-issues

As soon as I market "Women" it updated count to show the correct total.
![image](https://user-images.githubusercontent.com/8209966/67276278-a1648e80-f4c4-11e9-8bce-8a25ddbf606a.png)

That said, I think this issue can definitely be closed, nothing to do with mage2vuestorefront or magento2-vsbridge-indexer. 

Thank you for your time and sorry for bringing this up.
