### ISSUE TITLE
Not getting data of extension_attributes.downloadable_product_links in Elastic Search 

### ISSUE THREAD

**Issue by nitin-bc** [DivanteLtd/magento2-vsbridge-indexer#142]
Hello All,
I am facing an issue with the Vsbridge indexer. I am not getting data of extension_attributes.downloadable_product_links in ElasticSearch, while the same data I am able to get using mage2vs.
Anyone can help me with this?

**Comment by Hypo386** [comment]
I'll takie it

**Comment by Hypo386** [comment]
I.e there is product Beginner's Yoga 240-LV04

![image](https://user-images.githubusercontent.com/4815371/68938456-b7e9c700-079e-11ea-891e-0b492f657e3d.png)


mage2vs elasticsearch export contains section extension_attributes as follows 

```
               "extension_attributes":{ 
                  "downloadable_product_links":[ 
                     { 
                        "link_type":"file",
                        "price":6,
                        "is_shareable":2,
                        "link_file":"/l/u/luma_background_-_model_against_fence_4_sec_.mp4",
                        "id":1,
                        "title":"Beginner's Yoga",
                        "sort_order":1,
                        "sample_type":null,
                        "number_of_downloads":0
                     }
                  ],
                  "downloadable_product_samples":[ 
                     { 
                        "id":1,
                        "title":"Trailer #1",
                        "sort_order":1,
                        "sample_type":"file",
                        "sample_file":"/l/u/luma_background_-_model_against_fence_4_sec_.mp4"
                     },
                     { 
                        "id":2,
                        "title":"Trailer #2",
                        "sort_order":1,
                        "sample_type":"file",
                        "sample_file":"/l/u/luma_background_-_model_against_fence_4_sec_.mp4"
                     },
                     { 
                        "id":3,
                        "title":"Trailer #3",
                        "sort_order":1,
                        "sample_type":"file",
                        "sample_file":"/l/u/luma_background_-_model_against_fence_4_sec_.mp4"
                     }
                  ]
               }
```

This section is missing in magento2-vsbridge-indexer elasticsearch export.

Such section should be added

**Comment by Hypo386** [comment]
Added downloadable_product_links and downloadable_product_samples sections in magento2-vsbridge-indexer for elasticsearch.

Example dump from elastic:

`               "extension_attributes":{ 
                  "downloadable_product_links":[ 
                     { 
                        "id":"1",
                        "product_id":"47",
                        "sort_order":"1",
                        "number_of_downloads":"0",
                        "is_shareable":"2",
                        "link_url":null,
                        "link_file":"\/l\/u\/luma_background_-_model_against_fence_4_sec_.mp4",
                        "link_type":"file",
                        "sample_url":null,
                        "sample_file":null,
                        "sample_type":null,
                        "default_title":"Beginner's Yoga",
                        "store_title":null,
                        "title":"Beginner's Yoga",
                        "default_price":"6.0000",
                        "website_price":null,
                        "price":"6.0000"
                     }
                  ],
                  "downloadable_product_samples":[ 
                     { 
                        "id":"1",
                        "product_id":"47",
                        "sample_url":null,
                        "sample_file":"\/l\/u\/luma_background_-_model_against_fence_4_sec_.mp4",
                        "sample_type":"file",
                        "sort_order":"1",
                        "default_title":"Trailer #1",
                        "store_title":null,
                        "title":"Trailer #1"
                     },
                     { 
                        "id":"2",
                        "product_id":"47",
                        "sample_url":null,
                        "sample_file":"\/l\/u\/luma_background_-_model_against_fence_4_sec_.mp4",
                        "sample_type":"file",
                        "sort_order":"1",
                        "default_title":"Trailer #2",
                        "store_title":null,
                        "title":"Trailer #2"
                     },
                     { 
                        "id":"3",
                        "product_id":"47",
                        "sample_url":null,
                        "sample_file":"\/l\/u\/luma_background_-_model_against_fence_4_sec_.mp4",
                        "sample_type":"file",
                        "sort_order":"1",
                        "default_title":"Trailer #3",
                        "store_title":null,
                        "title":"Trailer #3"
                     }
                  ]
               },`

https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/161

**Comment by chakAs3** [comment]
> Added downloadable_product_links and downloadable_product_samples sections in magento2-vsbridge-indexer for elasticsearch.
> 
> Example dump from elastic:
> 
> `"extension_attributes":{ "downloadable_product_links":[ { "id":"1", "product_id":"47", "sort_order":"1", "number_of_downloads":"0", "is_shareable":"2", "link_url":null, "link_file":"\/l\/u\/luma_background_-_model_against_fence_4_sec_.mp4", "link_type":"file", "sample_url":null, "sample_file":null, "sample_type":null, "default_title":"Beginner's Yoga", "store_title":null, "title":"Beginner's Yoga", "default_price":"6.0000", "website_price":null, "price":"6.0000" } ], "downloadable_product_samples":[ { "id":"1", "product_id":"47", "sample_url":null, "sample_file":"\/l\/u\/luma_background_-_model_against_fence_4_sec_.mp4", "sample_type":"file", "sort_order":"1", "default_title":"Trailer #1", "store_title":null, "title":"Trailer #1" }, { "id":"2", "product_id":"47", "sample_url":null, "sample_file":"\/l\/u\/luma_background_-_model_against_fence_4_sec_.mp4", "sample_type":"file", "sort_order":"1", "default_title":"Trailer #2", "store_title":null, "title":"Trailer #2" }, { "id":"3", "product_id":"47", "sample_url":null, "sample_file":"\/l\/u\/luma_background_-_model_against_fence_4_sec_.mp4", "sample_type":"file", "sort_order":"1", "default_title":"Trailer #3", "store_title":null, "title":"Trailer #3" } ] },`
> 
> #161

Hi @Hypo386 , thank you for your work even though your pull request not yet merge. but i want to share with you some concerns, the  "extension_attributes" are mostly custom attributes that have been added to Original Core Magento Product, and the way you have added "extension_attributes" with two attributes "downloadable_product_links" and "downloadable_product_links"  means each time I have a specific attribute I have to add it same way to vsfbridge plugin core source which is not relevant and proper. in my opinion, it has to be some generic method that allows you to add all the extension_attributes, i hope that you get my point !

**Comment by enricodeleo** [comment]
I cannot see `extension_attributes ` data on version ^2. Is it abandoned feature or is there any other way to map data generated by extensions?

**Comment by enricodeleo** [comment]
🆙
