### ISSUE TITLE
Store specified attribute options of products not used in cronarea 

### ISSUE THREAD

**Issue by boehsermoe** [DivanteLtd/magento2-vsbridge-indexer#149]
When the indexer is running in cronarea only the option value from admin will be used and insert into the elasticsearch.
E.g. Product-A has a option "delivery_state" value **"red"** (admin value) and this option has the value **"rot"** in the storeview DE. 

## Actual result in Elasticsearch
```
{
    ...,
    delivery_state: "red"
}
```
## Expected result in Elasticsearch
```
{
    ...,
    delivery_state: "rot"
}
```

**Comment by afirlejczyk** [comment]
Hi @boehsermoe 
Did you mean value for a product attribute ?
What type of a attribute you have ? It's a text attribute ? 

What Magento version do you use ? What module version ?

> When the indexer is running in cronarea
Do you mean you have indexer set as "Update by schedule" ?

When you reindex data manually (from command line) you have correct data ?

**Comment by boehsermoe** [comment]
Hi @afirlejczyk you are right, only the option id will sync to elastic. This was the reason we wrote a own dataprovider to set the option text value instead of the id. In our plugin was the problem that the store id was not set to the attribute.

But this should be solved by the vsbridge indexer, because the option id is not useful in the frontend.

Our solution is following:

`
class AdditionalProductData  implements DataProviderInterface
{
    ...

    public function addData(array $indexData, $storeId)
    {
        $attributes = $this->resourceModel->loadAttributesData($storeId, array_keys($indexData), ['delivery_time']);

        $deliveryTimeAttribute = $this->resourceModel->getAttributeByCode('delivery_time');
        $deliveryTimeAttribute->setStoreId($storeId);

        foreach ($attributes as $entityId => $attributesData) {
            $productData = array_merge($indexData[$entityId], $attributesData);

            if (isset($attributesData['delivery_time']) && $attributesData['delivery_time']) {

                $optionId = $attributesData['delivery_time'];
                $productData['delivery_time'] = $deliveryTimeAttribute->getSource()->getOptionText($optionId);
            }

            $indexData[$entityId] = $productData;
        }

        $attributes = null;

        return $indexData;
    }
}
`

Instead to load only the delivery_time attribute, all attributes should be check with `$attribute->usesSource()` and load the option label text.

Or is there any reason to sync the option id?

**Comment by afirlejczyk** [comment]
@boehsermoe thanks for a feedback. 
By default VSF require only option id, real values are load from attribute type (from ES), where labels for a store view are exported.

You can do the same on VSF for a custom attribute and load attribute label from "attribute" type.

By default we won't be doing any changes regarding this attributes. @pkarw

**Comment by afirlejczyk** [comment]
I am closing this issue, because is not required by VSF core. @pkarw
