### ISSUE TITLE
Add support for color swatches

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/magento2-vsbridge-indexer#15]
Unfortunately, we can't easily get the color swatches from Magento using API

@afirlejczyk can You please take a look at this and propose some solution? I mean: we should probably put the swatches into attribute metadata and use it in VS frontend (currently we're just mapping the attribute label not using any other metadata)

**Comment by haelbichalex** [comment]
**FYI:** I'm trying to do this this week.
