### ISSUE TITLE
Add "final_price" to "configurable_children" to enable Catalog Price Rules

### ISSUE THREAD

**Issue by didkan** [DivanteLtd/magento2-vsbridge-indexer#151]
Hi guys and @afirlejczyk in particular!

I want to use Catalog Price Rules to discount products in Vue Storefront.
I can see the simple products get `final_price` exported to Elastic correctly but the `configurable_children` of a configurable product does not have the `final_price` at all. This means that Catalog Price Rules cannot be used in Vue Storefront if you are using configurable products.

When investigating this I found a comment from this commit:
https://github.com/DivanteLtd/magento2-vsbridge-indexer/commit/8eb09b53d5f0dd2fbc40da6aa8fc710e62b082ef#diff-7893eb8620a13730ae033dcc1d60c69eR163

So this would be the use case that makes it necessary to export `final_price` for configurable_children. @afirlejczyk 
Would it be possible to have this added?

**Comment by afirlejczyk** [comment]
Hi @didkan,

Yes it can be added, but I can't let you know when it will happen..  I will try to take a look into this later this week.

**Comment by didkan** [comment]
@afirlejczyk Hi! Any updates on above? Did you have time to check it out?

**Comment by afirlejczyk** [comment]
Hi @didkan 
Yes, I will push changes to develop branch later today.

**Comment by didkan** [comment]
@afirlejczyk 
Great! Thanks! I will start testing tomorrow then.

**Comment by afirlejczyk** [comment]
Merged with #156
