### ISSUE TITLE
Sort and filter by final_price

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/magento2-vsbridge-indexer#173]
Natively, VSF sorts and filters by final_price. However, almost each configurable product has **final_price equal 0**. Configurable children have proper final_prices. So if I am sorting by final_price every configurable product with final_price will be at the top, despite that his real price (from children) is much higher. 

In summary, it looks like it wasn't properly sorted. Same for filters. We need to fix it and set a proper final_price for configurable products.

**Comment by afirlejczyk** [comment]
https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/174/files - this should fix setting final_price.
I will check it later.

**Comment by Fifciu** [comment]
@afirlejczyk How to sort product properly if final_price could be 0? I am currently doing it by *price* but price does not count promotions, right?

**Comment by afirlejczyk** [comment]
I merged a fix to develop. 
Final price for configurable product is calculated base on children products, so you shouldn't have 0 any more. (for configurable products with final_price == 0) 

And yes, `price` does not count promotions only final_price.
