### ISSUE TITLE
Add support for url_path

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/magento2-vsbridge-indexer#18]
Starting with VS 1.9 the `url_path` is being used for the url routing (https://github.com/DivanteLtd/vue-storefront/pull/2446)

The new edition of M2VS is populating these fields by the customizable code snippet:
https://github.com/DivanteLtd/mage2vuestorefront/blob/349c19063264a3fd8dd68c62571b42e32a1e98e9/src/config.js#L5

We should set the `product.url_path` to normalized `$product->getUrl()` - with protocol, domain and leading `/` removed (so just the path without the leading slash); for category - not sure how magento does it by default but it should be just the default magento2 url path for category

**Comment by afirlejczyk** [comment]
Done.
https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/23

**Comment by dimasch** [comment]
`url_path` field not imported for simple products (PS: for parent configurable is exists)

Is correct?

Configurable sku: `WP12`
Simple sku: `WP12-28-Gray`

```
{"query":{"bool":{"must":[{"term":{"sku":"WP12-28-Gray"}}],"must_not":[],"should":[]}},"from":0,"size":10,"sort":[],"aggs":{}}
```

![2019-05-23_12-36-55](https://user-images.githubusercontent.com/414067/58238156-ce671680-7d57-11e9-8e28-bc63a0959a8b.png)

**Comment by dimasch** [comment]
Thanks, 
I found it related to `product.visibility` on client side. 
On SSR product opened correctly.
