### ISSUE TITLE
The `stock.product_id` is missing

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/magento2-vsbridge-indexer#187]
... we must add this field as it's used across different areas of Vue Storefront 

Details: https://forum.vuestorefront.io/t/using-magento2-vsbridge-indexer-instead-of-mage2vs/1093/2

**Comment by afirlejczyk** [comment]
Indexer doesn't export `stock.product_id` because it was not used by VSF core at the time.
I am not sure if VSF by default is using this field for some sorting? Nevertheless I made changes and `product_id` will be exported.
