### ISSUE TITLE
Wrong attribute casting for "include_in_menu"

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/magento2-vsbridge-indexer#188]
VSF is expecting true/false:

- Categories can be filtered in the Breadcrumbs, by setting `entities.category.breadcrumbFilterFields` in local.json, e.g. `"breadcrumbFilterFields": { "include_in_menu": true }`.

In ES i have: "include_in_menu": 1,

**Comment by afirlejczyk** [comment]
If you update your local.json to
```
"include_in_menu": 1
```
will it work? or VSF won't be able to handle this. ?

**Comment by simonmaass** [comment]
Yes it works but I thought that maybe it would be good streamline all values

**Comment by afirlejczyk** [comment]
Yes, I will close this one.
