### ISSUE TITLE
 Vsbridge Product Category Indexer error

### ISSUE THREAD

**Issue by marcelowu** [DivanteLtd/magento2-vsbridge-indexer#190]
![Screenshot from 2020-01-21 22-19-32](https://user-images.githubusercontent.com/30912144/72857380-3762ad80-3c9c-11ea-9eee-e5830a338806.png)
![Screenshot from 2020-01-21 22-19-06](https://user-images.githubusercontent.com/30912144/72857381-3762ad80-3c9c-11ea-96e2-fd15683872f0.png)
![Screenshot from 2020-01-21 22-18-30](https://user-images.githubusercontent.com/30912144/72857382-3762ad80-3c9c-11ea-96b3-899ffa2ded56.png)

Magento2.3.3 Nginx PHP7.2 Ubuntu 18 ES6

**Comment by afirlejczyk** [comment]
Duplicated issue.
Please check this:
https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/184

Everything is okay.
This a indexer using only for partial indexing (used only on product save), we should hide it in Magento panel.  More details here: https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/184
