### ISSUE TITLE
error: API call failed: Product with SKU

### ISSUE THREAD

**Issue by marcelowu** [DivanteLtd/magento2-vsbridge-indexer#192]
![Screenshot from 2020-01-22 22-48-45](https://user-images.githubusercontent.com/30912144/72950196-5ed37c00-3d69-11ea-801c-6bed5986db98.png)

**Comment by afirlejczyk** [comment]
This module is not responsible for VSF api, please add issue here:
https://github.com/DivanteLtd/vue-storefront-api/
