### ISSUE TITLE
magento2-vsbridge-indexer is not working with storefront-api and elastic search (ES7)

### ISSUE THREAD

**Issue by manimaran07** [DivanteLtd/magento2-vsbridge-indexer#195]
Getting below error,  when I trying to create a new index in elastic search ( ES7  -> localhost:9200)  

{"error":{"root_cause":[{"type":"parse_exception","reason":"unknown key [index.mapping.total_fields.limit] for create index"}],"type":"parse_exception","reason":"unknown key [index.mapping.total_fields.limit] for create index"},"status":400}

**Comment by afirlejczyk** [comment]
Did you test changes from branch **2.x**
Changes regarding ES 6+ are available in separated branch. More details here:
https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/147
