### ISSUE TITLE
Linked products (Related, Up-Sell, Cross-Sell) not properly indexed in ES. 

### ISSUE THREAD

**Issue by sudma** [DivanteLtd/magento2-vsbridge-indexer#196]
When adding any of the product link types (Related, Up-Sell, Cross-Sell) against the product, the incorrect logic for retrieving the linked product is implemented in indexing process`vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-catalog/Model/ResourceModel/Product/Links.php` file. 

Magento Commerce OOTB in `catalog_product_link` table under `product_id` column saves the value from `catalog_product_entity` table column `row_id` **NOT** the `entity_id` this is due to content staging feature. 
Sometimes the `row_id` in `catalog_product_entity`  can be the same as `entity_id` , but it's not a case always. 

When vsbridge indexer is filtering the products to be indexed and send to ES it applies the filtering based on `product_id` and not the `row_id` which is **not correct** logic.
Method is `prepareLinksSelect()`in the same file which applies the filtering logic.

Due to that it's possible that the incorrect product link mapping will be sent to ES `"products_links[]"` data.

**Comment by afirlejczyk** [comment]
Thanks for reporting the issue.
Indexer does not support Commerce Staging feature.
I am aware row_id can have different value than entity_id
I will take a look and check filtering logic for product links.
