### ISSUE TITLE
Admin configurations are not shwoing Magento ver. 2.3.3

### ISSUE THREAD

**Issue by badi238** [DivanteLtd/magento2-vsbridge-indexer#197]
Hi I have installed this extension but admin configurations are not showing have tried all commands as well removed cache, sessions folder still it's not showing on configurations.
I have checked extensions are installed on config.php
`'Divante_VsbridgeIndexerCore' => 1,
        'Divante_VsbridgeIndexerCms' => 1,
        'Divante_VsbridgeIndexerCatalog' => 1,
        'Divante_VsbridgeIndexerReview' => 1,
        'Divante_VsbridgeIndexerTax' => 1,`

**Comment by afirlejczyk** [comment]
I didn't occur to this problem on Magento 2.3.3 either on Magento 2.3.4

I only did:
- composer install
- `php bin/magento setup:upgrade` (all modules where enabled in config.php)
- clear cache: `php bin/magento cache:flush` 

Configuration is visible in Magento Admin panel.
