### ISSUE TITLE
Add url_key/url_path from different store views

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/magento2-vsbridge-indexer#198]
It is so useful for SEO stuff. Clients often want to have corresponding hreflangs. For real, we have ready code as extension for indexer. We could share it but it needs that: https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/182

I would appreciate merge it because with that we could easily modify saving data (which we do the mostly) and confidently pull the new updates.

**Comment by afirlejczyk** [comment]
1. You can easily add or modify data by adding new data providers in vsbridge_indices.xml 
2. There will be some new changes merge to develop.
https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/185 (there will be some interfaces you can use in your implementations)
3. I don't plan to expose constructor properties.
