### ISSUE TITLE
Double check the multi attributess

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/magento2-vsbridge-indexer#20]
https://github.com/DivanteLtd/mage2vuestorefront/pull/69

**Comment by afirlejczyk** [comment]
I will check, but it is working. :)
I have to do small fixes for vsf
https://github.com/DivanteLtd/vue-storefront/pull/2379/files

**Comment by afirlejczyk** [comment]
It is working, multiselect attributes are exported as array.
Example from sample Magento data:
```
   "material": [
      "44",
      "45"
    ],
    "gender": [
      "80",
      "81",
      "84"
    ],
```

I am closing this issue.
