### ISSUE TITLE
vsbridge:reindex --all don't work

### ISSUE THREAD

**Issue by Abdoul19** [DivanteLtd/magento2-vsbridge-indexer#214]
Hi after config I try to reindex like this :

php bin/magento vsbridge:reindex --all
Reindexing all stores...Reindexing store Default Store View...In Connection.php line 636:                                                                                           {"error":{"root_cause":[{"type":"parse_exception","reason":"unknown key [index.mappin    g.total_fields.limit] for create index"}],"type":"parse_exception","reason":"unknown     key [index.mapping.total_fields.limit] for create index"},"status":400}

**Comment by afirlejczyk** [comment]
Hi,

Which branch do you use and which ES version?
It working just fine with ES 5.6

**Comment by afirlejczyk** [comment]
Support for ES6+ is available in 2.x branch.
