### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by ninjacoder30** [DivanteLtd/magento2-vsbridge-indexer#217]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofphp/php-cs-fixer v2.13.3 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.3.13) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.3 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.3.13) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.3 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.3.13) does not satisfy that requirement.
    - Installation request for friendsofphp/php-cs-fixer (locked at v2.13.3, required as ~2.13.0) -> satisfiable by friendsofphp/php-cs-fixer[v2.13.3].

Installation failed, reverting ./composer.json to its original content.

**Comment by afirlejczyk** [comment]
Hello,

Without some details I don't think how anyone can help. 
Which module version (branch) you try to install? Which Magento version do you use? 
Module does not have direct dependencies for `friendsofphp/php-cs-fixer`

**Comment by saigadekar** [comment]
Hi 
I am using
 "magento/product-community-edition": "2.3.3"
and PHP version is 7.3

**Comment by afirlejczyk** [comment]
I installed module on Magento 2.3.3, with PHP 7.3 and didn't have this problem.
Do you checked this on clean Magento installation?
