### ISSUE TITLE
Indexers not running when new review is created

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/magento2-vsbridge-indexer#233]
If a new review is created it does not update Elastic Search

**Comment by afirlejczyk** [comment]
Hi @simonmaass

Last I checked it worked - nothing has changed for reviews for quite some time.
We have plugin on `afterSave` and subscription in `mview.xml`

https://github.com/DivanteLtd/magento2-vsbridge-indexer/blob/develop/src/module-vsbridge-indexer-review/Plugin/Indexer/Review/Save/UpdateReview.php

https://github.com/DivanteLtd/magento2-vsbridge-indexer/blob/develop/src/module-vsbridge-indexer-review/etc/mview.xml

Which Magento version do you use ?

**Comment by simonmaass** [comment]
@afirlejczyk thnx for reploy - we are using 2.3.4 - i will debug it in more depth again

**Comment by afirlejczyk** [comment]
Only approved reviews are exported, I just check it on Magento 2.3.0 and it's working.
If you are using on schedule mode I would check if triggers were created.
