### ISSUE TITLE
Need help reindex nothing.

### ISSUE THREAD

**Issue by gfd6th** [DivanteLtd/magento2-vsbridge-indexer#237]
Magento ver 2.3.2.
This is my configs in magento.
![Jietu20200314-112211@2x](https://user-images.githubusercontent.com/6814715/76674022-15274500-65e6-11ea-96d1-29e6a68ed100.jpg)

And the reindex command:
![Jietu20200314-112451@2x](https://user-images.githubusercontent.com/6814715/76674080-8535cb00-65e6-11ea-90cf-478e76990cdf.jpg)

But there is no vue_storefront_cataog in es
![Jietu20200314-112555@2x](https://user-images.githubusercontent.com/6814715/76674101-ae565b80-65e6-11ea-8cab-f3131f4b3cca.jpg)

![Jietu20200314-112740@2x](https://user-images.githubusercontent.com/6814715/76674130-db0a7300-65e6-11ea-805d-ea2224b16601.jpg)

**Comment by pkarw** [comment]
@afirlejczyk can you please take a look?

**Comment by afirlejczyk** [comment]
Hi.

Firstly, did you clear Magento cache after changing configuration?
Depends on which store view you are trying reindex (by default only Default Magento Store View will be reindex), you should have in ES index like so:

`vue_storefront_catalog`, `vue_storefront_catalog_2`, `vue_storefront_catalog_3`, etc.

1. You can check directly in ES what aliases has been created:
`GET /_cat/aliases`  
https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-alias.html

2. You can use custom command 
`vsbridge:reindex` to run reindex for vsbridge indices. At the end you will get info about created indices (name and alias).

```
php bin/magento vsbridge:reindex --store [STORE_CODE
```
Sample result:
```
www-data@1423273f0eb3:~$ php bin/magento vsbridge:reindex --store default
Reindexing all VS indexes for store Default Store View...
Vsbridge Cms Block Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Cms Page Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Product Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Category Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Attributes Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Tax Rule Indexer index has been rebuilt successfully in 00:00:00
Index name: vue_storefront_catalog_1584365396, index alias: vue_storefront_catalog
Reindexing has completed!
```



magento2-vsbridge-reindex is an alternative tool to https://github.com/DivanteLtd/mage2vuestorefront - so you shoulnd't run `yarn db rebuild` after that.

**Comment by gfd6th** [comment]
@afirlejczyk Thanks for your help, I think I have found the problem caused by my elasticsearch
