### ISSUE TITLE
Category Product Indexer not available from command line

### ISSUE THREAD

**Issue by dverkade** [DivanteLtd/magento2-vsbridge-indexer#238]
Hi,

I've just wasted a couple of hours of my life on the following. I was trying to run the following index, which is listed in the indexers:
![image](https://user-images.githubusercontent.com/1058480/76872199-65afd400-686c-11ea-9098-75d6eabdd03c.png)

However the index won't return any result. Eventually I came across this code. It just removed the indexer from the array of indexes to run:
![image](https://user-images.githubusercontent.com/1058480/76872257-7ceec180-686c-11ea-8006-8a7d978cf99e.png)

I don't know why it behaves this way. This will result in the index not being able to run individually, as well as not being to run as a dependent.

**Comment by afirlejczyk** [comment]
https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/190
https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/184

> It was done by purpose. It's only used for partial indexing and meant to be use only on category save - in "Save mode" for Vsbridge Category Indexer.
> If you are using "On Schedule" for category indexer, this indexer is not useful.

**Comment by dverkade** [comment]
@afirlejczyk that's just not the way this should work and it's not best practice either. You should either have the ability to run the index, or at least throw an error or notice that this index can't be run individually. I've now been debugging this for a couple of hours because it didn't give me an error and it couldn't find anything in the system.log or anywhere else.

**Comment by afirlejczyk** [comment]
I re-opened issue: https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/184
So I am closing this and #240 issue. 
I will later decide what to do.
