### ISSUE TITLE
Base Configuration for Magento Backend

### ISSUE THREAD

**Issue by domideimel** [DivanteLtd/magento2-vsbridge-indexer#243]
When we started to develop our own theme in VSF our Data came from the demo page thats provided during installation.
After changing from the Demo Magento to our own Magento 2 with the Same dummy data the behavior of our app changed drastically. Even the provided default theme behaved in a different way than it used to.
I encountered some options were not set properly in our backend to provide all the data the app needs.

So bottom line: When starting devloping our URL's looked something like this `localhost:3000/women/tops-women/tanks-women/bras-and-tanks-26/chloe-compete-tank-1769.html?childSku=WT06-XS-Blue` and after switching to our own Magento the very same product url looks like this `localhost:3000/circe-hooded-ice-fleece?childSku=WH12-XS-Gray`.

Could you provide a basic Configuration for your extension and perhaps for the SEO Settings for the catalog that the default theme behaves like with the demo data?

**Comment by afirlejczyk** [comment]
There is no options for that.

- url suffix, like ".html" is stripped during exported data to elasticsearch. This should be changed - we should export url_path with suffixes (base on Magento Catalog configuration:  Catalog -> Catalog-> Search Engine Optimization -> Product URL Suffix, Category URL Suffix ) 

- vsf-api (mage2vuestorefront) generate `url_path` for products in different way then magento2-vsbridge-indexer.  I guess https://github.com/DivanteLtd/mage2vuestorefront tool does not have access to Magento urls, so it generate urls "manually". 

In magento2-vsbridge-indexer `url_path` is generated base on Magento URLs.
**Url in VSF are consistent with Magento2 urls (minus this bug with missing url suffixes)**. (products can have multiple valid URL's, for example: different urls base for categories - but it depends on Magento Catalog configuration).

Bottom line: for products - "clean" `url_path` are exported from `url_rewrite` table.

```
+----------------+-------------+-----------+-----------------------------------------------------------------------------+------------------------------------------+---------------+----------+-------------+------------------+----------------------+
| url_rewrite_id | entity_type | entity_id | request_path                                                                | target_path                              | redirect_type | store_id | description | is_autogenerated | metadata             |
+----------------+-------------+-----------+-----------------------------------------------------------------------------+------------------------------------------+---------------+----------+-------------+------------------+----------------------+
|            387 | product     |      1215 | circe-hooded-ice-fleece.html                                                | catalog/product/view/id/1215             |             0 |        1 | NULL        |                1 | NULL                 |
|            396 | product     |      1215 | women/tops-women/hoodies-and-sweatshirts-women/circe-hooded-ice-fleece.html | catalog/product/view/id/1215/category/24 |             0 |        1 | NULL        |                1 | {"category_id":"24"} |
|            397 | product     |      1215 | collections/performance-fabrics/circe-hooded-ice-fleece.html                | catalog/product/view/id/1215/category/35 |             0 |        1 | NULL        |                1 | {"category_id":"35"} |
|           1083 | product     |      1215 | circe-hooded-ice-fleece.html                                                | catalog/product/view/id/1215             |             0 |        2 | NULL        |                1 | NULL                 |
|           1084 | product     |      1215 | women/tops-women/hoodies-and-sweatshirts-women/circe-hooded-ice-fleece.html | catalog/product/view/id/1215/category/24 |             0 |        2 | NULL        |                1 | {"category_id":"24"} |
|           1085 | product     |      1215 | collections/performance-fabrics/circe-hooded-ice-fleece.html                | catalog/product/view/id/1215/category/35 |             0 |        2 | NULL        |                1 | {"category_id":"35"} |
|           1086 | product     |      1215 | women/tops-women/circe-hooded-ice-fleece.html                               | catalog/product/view/id/1215/category/21 |             0 |        2 | NULL        |                1 | {"category_id":"21"} |
+----------------+-------------+-----------+-----------------------------------------------------------------------------+------------------------------------------+---------------+----------+-------------+------------------+----------------------+
7 rows in set (0.01 sec)

```

"Clean url" -> record, where `target_path` match pattern:  `catalog/product/view/id/[ID]` 
So for this products you have `url_path`: `circe-hooded-ice-fleece`

If you want to have different url_path for products -> you have to change exported values for "url_path" field.

**Comment by afirlejczyk** [comment]
I added changes to export Magento suffixes for categories/products.
https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/247
