### ISSUE TITLE
Problem with indexing categories in ES

### ISSUE THREAD

**Issue by joshuaregio018** [DivanteLtd/magento2-vsbridge-indexer#246]
After I successfully executed the indexer commands in my terminal, I found out that not all categories are indexed in ES. Categories that are in level 2 are completely missing and some categories from level 3 and 4 are also missing.

I hope for your response. Thanks!

**Comment by afirlejczyk** [comment]
I never experience such behavior, always all categories has been exported. I have not idea why in your case some categories are missing. I can't help you more.

**Comment by revlis-x** [comment]
Hm same here, only categories with NO children are exported.

**Comment by afirlejczyk** [comment]
If you can reproduce this problem on clean Magento 2 then I check where might be a problem. 
If not - you have to check yourself.
