### ISSUE TITLE
After adding new attribute the mapping is not created, breaks whole catalog if used in VSF filters.

### ISSUE THREAD

**Issue by kustraszymon** [DivanteLtd/magento2-vsbridge-indexer#265]
Hi,
we have added varchar attribute named "pantone_color" and want it in filters. Everything is reindexed globally. It does not work, causes catalog to break. Error:

> type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"vue_storefront_magento_12_1579771351","node":"6ls5ck-vTtSzuZ9IfsApOQ","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [pantone_color] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}]} 

In the code there is "TODO" left by the author @afirlejczyk

`\Divante\VsbridgeIndexerCatalog\Plugin\Indexer\Attribute\Save\UpdateAttributeDataPlugin::afterAfterSave`

> TODO check if we add new attribute, after adding new attribute send request to elastic to add new mapping

Clearly it doesn't ;)

===========================

> GET vue_storefront_magento_11/_mapping/product_eav 

returns no mapping for that attribute

![image](https://user-images.githubusercontent.com/6999517/80588713-2226b900-8a19-11ea-96c8-1cb794566276.png)

===========================

Another issue is that reindex does not solve it. Nor full reindex by vsbridge:reindex nor by bin/magento indexer:reindex. It's unfixable.

It works only when index is deleted and re-created.

============================

> DELETE vue_storefront_magento_11

> bin/magento vsbridge:reindex --store=11

> GET vue_storefront_magento_11/_mapping/product_eav 

![image](https://user-images.githubusercontent.com/6999517/80588902-7b8ee800-8a19-11ea-91e7-33a23ba2a6c0.png)

**Comment by afirlejczyk** [comment]
```
TODO check if we add new attribute, after adding new attribute send request to elastic to add new mapping
```
Yes it a new feature, TODO in a future.

Yes, mapping is only added when new index is build.
You can use `vsbridge:reindex --all` (or `vsbridge:reindex --store 11) command to re-create indicies (new mapping then will be applied).

**Comment by benoitemile** [comment]
Hi @afirlejczyk , how should one proceed to update mapping ? 
First indexation with attribute as select
Then, for some reason, attribute is changed to a text field

Then that error : 

> Fielddata is disabled on text fields by default. Set fielddata=true on [xxxxx] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.

Tried deleting all indicies but error still persists
