### ISSUE TITLE
Add posibility to trigger external webhook to sync other data 

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/magento2-vsbridge-indexer#266]
Hey,

we are using prismic as CMS and if i do a full reindex it would be great if you had to possibility to trigger a webhook for example to also sync other services like prismic for example...

**Comment by DavidLambauer** [comment]
Hi, this issue could be closed by merging [PR 280](https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/280)

**Comment by simonmaass** [comment]
@afirlejczyk this would help a lot

**Comment by DavidLambauer** [comment]
@simonmaass You can close this issue as our PR was merged.

**Comment by simonmaass** [comment]
thnx!
