### ISSUE TITLE
Not excluding attributes from category

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/magento2-vsbridge-indexer#267]
Hey

I only selected a couple of attributes for category:

![export_category](https://user-images.githubusercontent.com/32599710/80698053-37afe780-8ada-11ea-9888-7792c3629920.png)

But in export all attributes are present:

![export](https://user-images.githubusercontent.com/32599710/80698067-3f6f8c00-8ada-11ea-81b9-1c2df5acee7b.png)

**Comment by afirlejczyk** [comment]
Hi,

Strange.
Did you run full reindex after you change/setup configuration? Just to make sure - clean cache (for configuration) before doing that.

**Comment by afirlejczyk** [comment]
Fix in **1.16.1**
