### ISSUE TITLE
Impossible to disable a product

### ISSUE THREAD

**Issue by Fifciu** [DivanteLtd/magento2-vsbridge-indexer#272]
If the moderator disables product after the first reindex - it will not be disabled in the ES. I mean that value of `status` attribute won't be changed to `2` (disabled).

I believe the source of problem is in the class `StatusSelectModifier`, in this line:
```
)->where($checkSql . ' = ?', Status::STATUS_ENABLED);
```

You filter products and leave only ones that are enabled. Unfortunately, this way it won't update `status` attribute of products I've just disabled.

My quickfix for that was changing line above to the:
```
)->where($checkSql . ' IN (?)', array(Status::STATUS_ENABLED, Status::STATUS_DISABLED));
```
Unfortunately, it slows down reindex significantly so I believe there is a better way to fix it. It also does not send invalidate request

**Comment by afirlejczyk** [comment]
Disabled products are note exported to ES at all. Products with status disabled are automatically removed from ES. I don't plan to change this behavior. 

So if I change the product from Enabled to Disable - the product should disappear from ES all together. 
This is how it works from the beginning. I might check if sth didn't break the meantime.

**Comment by afirlejczyk** [comment]
I just did a quick test - I disable product in Magento backend and it disappears from ES.
Before:
![screenshot-localhost_5601-2020 05 11-07_00_11 (1)](https://user-images.githubusercontent.com/4245592/81525497-3477ef80-9355-11ea-9302-4ac1b907bf52.png)


After:
![screenshot-localhost_5601-2020 05 11-07_00_11](https://user-images.githubusercontent.com/4245592/81525495-32159580-9355-11ea-80fa-760d5e4b7684.png)

**Comment by simonmaass** [comment]
can confirm

**Comment by Fifciu** [comment]
Hmmm maybe it is related to some of my custom modification... Could you please make sure invalidate cache for just disabled item also works properly? @afirlejczyk @simonmaass

**Comment by afirlejczyk** [comment]
Yes, it is. The request for invalidating cache is sent.
