### ISSUE TITLE
Problem with uploading data

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/magento2-vsbridge-indexer#274]
### When uploading data from magento 2.3 to Elasticsearch 7.3, I get an error

![Screenshot_from_2020_05_13_20_18_51](https://user-images.githubusercontent.com/20755897/81830616-ec75ea00-9559-11ea-8c5a-e762cd235c25.jpg)

### In the beginning, I prepared the vue storefront api configuration

![Screenshot_from_2020_05_13_20_20_40](https://user-images.githubusercontent.com/20755897/81831495-0d8b0a80-955b-11ea-89c1-7ba27f99f963.jpg)

### Then, prepared vue storefront

![Screenshot_from_2020_05_13_20_20_35](https://user-images.githubusercontent.com/20755897/81831747-5c38a480-955b-11ea-9b88-2bda8c0e0e21.jpg)

### And finally, Before uploading data to ES7, I prepared the following configuration in magento 2.3

![Configuration_Settings_Stores_Magento_Admin](https://user-images.githubusercontent.com/20755897/81831982-986c0500-955b-11ea-97bd-0397a406743e.jpg)

### Accordingly, I get a result with a lack of data.

![Screenshot_from_2020_05_13_20_18_59](https://user-images.githubusercontent.com/20755897/81832204-d9fcb000-955b-11ea-8e5e-52e9f99f09d6.jpg)

**Something went wrong? Help me to understand**

**Comment by afirlejczyk** [comment]
If you are using ES 7, You have to use changes from branch `2.x` 

Changes in main branch, are compatible only with ES 5.

**Comment by ArieRym** [comment]
Reinstalled magento 2.3, then installed magento2-vsbridge-indexer version 2.x for ES7 and while running the command: "php bin / magento setup: upgrade" I get this result

![Screenshot_from_2020_05_16_21_00_58](https://user-images.githubusercontent.com/20755897/82123895-7b347200-97b9-11ea-9a06-b2b0e8acdc0b.jpg)
And still no new indexes appear in ES

And accordingly, with the launch of the command "bin / magento indexer: reindex"

![Screenshot_from_2020_05_13_20_18_51](https://user-images.githubusercontent.com/20755897/82124000-0a418a00-97ba-11ea-9c74-072fc42b8a05.jpg)

**Why is it still not working?**

**Comment by ArieRym** [comment]
So what should I do?

**Comment by ArieRym** [comment]
Hi @afirlejczyk 
I installed magento 2.3.3 Full Release with Sample Data. Further, installed magento2-vsbridge-indexer version 2.x

In the folder "vue-api", I ran the following commands
```
1. rm -f ./var/catalog*
2. npm run dump -- --input-index=vue_storefront_magento_1
3. npm run db rebuild -- --indexName=vue_storefront_magento_1
```

In the magento folder, I ran the following command
`bin/magento indexer:reindex`

![Screenshot from 2020-06-04 23-06-11](https://user-images.githubusercontent.com/20755897/83794958-5fd3cd00-a6bc-11ea-9866-1f3ef9aca55e.png)

But do not see new indexes. Elasticsearch is empty.

![Screenshot from 2020-06-04 22-57-12](https://user-images.githubusercontent.com/20755897/83795008-737f3380-a6bc-11ea-922f-c4e7dbefff14.png)

**What have I done wrong?**

**Comment by afirlejczyk** [comment]
The first index from the list - is an index you created using vue-api tool.
If you want to use this module, you don't have to use vue-api to import data, it's an alternative solution. More about this you will ask on VueStorefront slack/forum (they will tell you more about vue-api)


Regarding this particular extension...
I have no idea why you have empty indices, it looks like indexing product data take about 13 seconds.. so you should have some data.
Did you try to remove all indices and reindex (using `bin/magento indexer:reindex
or bin/magento vsbridge:reindex --store [STORE]` command)
? 

Did you check any logs for errors?
You should have some logs in `[magento-dir]/var/log/vsbridge-indexer/` folder

**Comment by ArieRym** [comment]
@afirlejczyk The first index created this is a command: bin/magento indexer:reindex

I cleaned up ES7 and ran bin/magento indexer:reindex

![14](https://user-images.githubusercontent.com/20755897/83888393-6408f480-a767-11ea-9e91-9155215a9d25.jpg)


I cleaned up ES7 and ran bin/magento vsbridge:reindex --store 1
In Connection.php line 636:
                                                                               
```
  {"error":{"root_cause":[{"type":"parse_exception","reason":"unknown key [in  
  dex.mapping.total_fields.limit] for create index"}],"type":"parse_exception  
  ","reason":"unknown key [index.mapping.total_fields.limit] for create index  
  "},"status":400}   
```

**Comment by afirlejczyk** [comment]
If you are exporting data to ES 7, **you have use branch 2.x**, the main branch will only work with ES5.

IN ES6+ lots of change, one of them is you can have **only one type per index**
That's why you have these errors.


When using changes from the second branch, you should have separated index per type..
(vue_storefront_magento_1_taxrule, vue_storefront_magento_1_category, etc..)
Base on the previous screen it had worked..
https://user-images.githubusercontent.com/20755897/83795008-737f3380-a6bc-11ea-922f-c4e7dbefff14.png

I am not able to help you more in this matter.

**Comment by ArieRym** [comment]
@afirlejczyk I have use branch 2.x. Ok I only care about this issue, I used to use mage2vuestorefront, but now I like your solution more. How to make such divisions vue_storefront_magento_1_taxrule, vue_storefront_magento_1_category, etc.

**Comment by afirlejczyk** [comment]
you don't have to use `mage2vuestorefront` and `yarn db new` command at all with this extension.

if you are on 2.x branch and you run command for example
```
bin/magento vsbridge:reindex --store 1
```
you should get index and data in ES.

Sample:
```
app@a6b3a6f5ad70:~/html$ php bin/magento vsbridge:reindex --store 1 
Reindexing all VS indexes for store Default Store View...
Vsbridge Product Indexer index has been rebuilt successfully in 00:00:01
Vsbridge Category Indexer index has been rebuilt successfully in 00:00:10
Vsbridge Attributes Indexer index has been rebuilt successfully in 00:00:03
Vsbridge Cms Block Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Cms Page Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Review Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Tax Rule Indexer index has been rebuilt successfully in 00:00:00
Reindexing has completed!
```

screenshots from elasticsearch:
_http://localhost:9200/_cat/indices_
![es-indicies](https://user-images.githubusercontent.com/4245592/83919152-4e50fa80-a77a-11ea-8c60-bbc5c4f35c65.png)

_http://localhost:9200/_cat/aliases_
![es-aliases](https://user-images.githubusercontent.com/4245592/83919156-50b35480-a77a-11ea-823d-3574aa7a7d30.png)
