### ISSUE TITLE
Index name in elastic has id prefixed, even is set not to

### ISSUE THREAD

**Issue by ProxiBlue** [DivanteLtd/magento2-vsbridge-indexer#279]
Hello,
Is there a bug here, or am I missing something?
In m2, settings are as follows:

![Selection_550](https://user-images.githubusercontent.com/4994260/82396112-b49e0380-9a7f-11ea-96f7-cc2fe0e4762a.png)

my expectation is that the index in elastic should simply just be: vue_storefront_enjo
However, what I get is an index post-fixed with some id. (which is not the store id)

![Selection_551](https://user-images.githubusercontent.com/4994260/82396192-e3b47500-9a7f-11ea-8ab9-3abe160e3aba.png)

**Comment by ProxiBlue** [comment]
02:08 $ composer show -i |grep divante
You are using the deprecated option "installed". Only installed packages are shown by default now. The --all option can be used to show all packages.
divante/magento2-vsbridge-indexer                                 1.16.1           
divante/magento2-vsbridge-indexer-msi                             0.1.0              Extension for magento2-vsbridge-indexer. Support for MSI

**Comment by afirlejczyk** [comment]
```
my expectation is that the index in elastic should simply just be: vue_storefront_enjo
```
Yes, for a default store view you should have a simple alias - without store code.
You have to check aliases - not index names in ES. 
```
http://localhost:9200/_cat/aliases
```
you should have clear aliases(names) there.

**Comment by ProxiBlue** [comment]
> Yes, for a default store view you should have a simple alias 

Hello, thanks for the response, but the result is not as such. 

There is only the one index, and it has that code postfixed (whatever it is)
There is no index with no prefix.

Your example shows that ID postfixed to a version of teh index witha store id _1_
So, what exactly IS that new ID that appears at teh end of the index name?
Also, it seems to change.

So, if I delete all indexes, and fully re-index, I then have to go edit all the vuesf config files, to place the new index name. 

This seems wrong.

below, I wiped all indexes: (I renamed index to _magento_ for these):

```
curl -X DELETE "elastic.***.com/*"
```

Then reset all magento indexes:

```
php ./bin/magento index:reset
```

ran indexes

```
php ./bin/magento index:reindex
```

and checked the end result:

```
ubuntu@ip-172-31-40-124:/var/www/html/current$ curl -X GET "elastic.656ea.com/_cat/indices/*?v&s=index&pretty"
health status index                             uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   magento2_product_1_v2             0v1pEKzKRIeJCj9AzO_zpg   5   1        225            0    567.9kb        567.9kb
yellow open   magento2_product_2_v2             CvwbJbxISiykgCC4CAwTpw   5   1        222            0    564.3kb        564.3kb
yellow open   magento2_product_4_v2             f8hJ2WlDQw6c0rqPsQ8QPA   5   1        184            0      488kb          488kb
yellow open   vue_storefront_magento_1590030275 zcx2KmYVSACj9YC7SBncrw   5   1          0            0      1.1kb          1.1kb

```

If I go change settings, to include the STORE CODE, I get:

```
ubuntu@ip-172-31-40-124:/var/www/html/current$ curl -X GET "elastic.656ea.com/_cat/indices/*?v&s=index&pretty"
health status index                                     uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   magento2_product_1_v2                     IoZBIXnUSx2zGhpCrdTWqQ   5   1        225            0      586kb          586kb
yellow open   magento2_product_2_v2                     LlG7ATs7TX-gsSJ_rF1f_w   5   1        222            0    564.3kb        564.3kb
yellow open   magento2_product_4_v2                     uAPZfRMqSAGpyaeoHzaElA   5   1        184            0    467.4kb        467.4kb
yellow open   vue_storefront_magento_default_1590030943 IUtpGncGTbibUueMYvhiig   5   1          0            0      1.1kb          1.1kb
```

and the same for setting to use id.

Now, lets take that first result that was:
vue_storefront_magento_1590030275

wipe indexes, and rerun magento index:

the new index is now:

vue_storefront_magento_1590031292

so, changed
As noted above, this then requires vuesf and api configs to be edited, a deploy must be done to get that out, that must build etc etc

downtime

It makes no sense.

What is that id for? or what am I missing here?

**Comment by ProxiBlue** [comment]
I completely missed that bit: 

> You have to check aliases - not index names in ES.

That is what I was misisng.

Thanks
