### ISSUE TITLE
Empty attribute value on store level is ignored, the value from global scope is reindexed. 

### ISSUE THREAD

**Issue by sudma** [DivanteLtd/magento2-vsbridge-indexer#284]
Checked on module version: **1.16.1**

Even though the indexing works fine if the product attribute value is changed on store level and has value in contrast to the global scope level, the correct attribute value which is set on store-level is indexed in ES.

But, if the attribute value on the store level is deleted, or set empty the value from global scope is reindexed. 

**Steps to replicate**
Add any custom attribute type varchar and on global scope set any value for this attribute, after that on store-level scope change the attribute value to NULL (delete value from admin input interface) and check the value in ES. 
I am expecting to see the NULL value indexed in ES because on my store scope I have overwritten the attribute value from the global scope. 

**Expected behavior**
The value NULL from store level will be indexed in ES.

**Actual Behavior**
The value from global scope is indexed in ES.

**Comment by afirlejczyk** [comment]
Fix with #313, changes are available in master branch
