### ISSUE TITLE
I can not install magento2-vsbridge-indexer

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/magento2-vsbridge-indexer#288]
@afirlejczyk  I am trying to install again from https://github.com/DivanteLtd/magento2-vsbridge-indexer/tree/2.x
but I get an error during installation

![Screenshot_from_2020_06_06_08_32_27](https://user-images.githubusercontent.com/20755897/83940749-12627780-a804-11ea-8c10-ed60cfdd53db.jpg)

From the second branch, it must support es7, why then it is not installed

**Comment by afirlejczyk** [comment]
https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/88
