### ISSUE TITLE
magento catalog depends

### ISSUE THREAD

**Issue by nagrgkgc** [DivanteLtd/magento2-vsbridge-indexer#290]
Hi Team,

Please add in all dependencies in JSON and module.xml to support fresh installation.
Magento fresh installation fails with VSBRIDGE module install.

Module 'Divante_VsbridgeIndexerCatalog':
Upgrading data... 
                                                    
[Magento\Framework\Exception\LocalizedException]  
Invalid entity_type specified: catalog_product 

is it possible to add sequence in module.xml and push changes to this repo ?

Thank you

**Comment by afirlejczyk** [comment]
Hi,
Sure, I will push a fix. I notice a problem recently but forgot to make a fix.

**Comment by afirlejczyk** [comment]
the fix is available in 1.18.0

**Comment by nagrgkgc** [comment]
Thank you
