### ISSUE TITLE
Indexer clearing all data

### ISSUE THREAD

**Issue by nagrgkgc** [DivanteLtd/magento2-vsbridge-indexer#295]
Hi Team,

We have installed VSBridge and running crons for multiple storeviews with 
php bin/magento vsbridge:reindex --store=[STORE ID|STORE CODE], we have setup every 15mins for 10 store views in single magento store.

issue is that, 
we get indexes build for every store views. as it get build, other store views indexes being deleted and makes doc count = 0.

please see below screenshot:
<img width="1122" alt="Screen Shot 2020-06-15 at 10 56 11 AM" src="https://user-images.githubusercontent.com/53718686/84626905-01e28900-aef7-11ea-8dff-8d632bc968b0.png">

Please let us know if any issue in configuring here or its clean and build?
it should be overwritten always than delete. 

Please check

**Comment by janmyszkier** [comment]
@afirlejczyk looks like https://github.com/DivanteLtd/magento2-vsbridge-indexer/blob/master/src/module-vsbridge-indexer-core/Index/IndexOperations.php#L206
should also check for the currently running store? (so one store reindex command using `--store=EN` doesn't remove another stores indexes)

**Comment by afirlejczyk** [comment]
@nagrgkgc

You don't have to set up any extra cronjobs.

Magento Cron jobs - responsible for reindexing data will take care for reindexing. Just setup indexers as an update on schedule and you should have updated data in ES.
Updating data in ES is build base on Magento indexers.

If you will have running extra cron jobs, and Magento Cron jobs at the same time - I have no idea what repercussions it might have.

This command was introduced mostly to easier run full reindex for specific one store view from command line.

**Comment by nagrgkgc** [comment]
@afirlejczyk 

Thank you for reply and all support. but if Magento runs indexes, will data synchronize in delta mode or complete index?

and if i have 10 store views, how much time for completing index? not sure if delta or complete index.

(if this synchronize all data (not by delta), which means I have 1 store view taking 10mins to index, and 10 would take 1 hr and 40 mins, am I right?)

Please explain. thank you

**Comment by janmyszkier** [comment]
@afirlejczyk 
 **if Magento runs indexes, will data synchronize in delta mode or complete index?**
last time I checked it was per-record (so: delta)

**how much time for completing index? not sure if delta or complete index.**
this depends ONLY on your infrastructure, so not something afirlejczyk can answer

**(if this synchronize all data (not by delta), which means I have 1 store view taking 10mins to index, and 10 would take 1 hr and 40 mins, am I right?**
that's a valid calculation

**Comment by nagrgkgc** [comment]
@janmyszkier 

i am still investigating and will give numbers here for everyones visibility.

Thank you

**Comment by afirlejczyk** [comment]
@janmyszkier 
> should also check for the currently running store? (so one store reindex command using --store=EN doesn't remove another stores indexes)

It only switches alias for currently indexing store... it doesn't touch other indices (for other store views).

**Comment by nagrgkgc** [comment]
@afirlejczyk 

you will have to have magento crons running with
hard coded another storewise index which would end up with above scenario.

i had hardcoded storewise index every 15mins and magento index for every min.

yes, it was ES5.6

**Comment by afirlejczyk** [comment]
OK, so you have to manage a solution for this yourself. As I mentioned earlier, this command wasn't designed to be run as cron job.

**Comment by nagrgkgc** [comment]
@afirlejczyk 

we have removed index from cron and relying on magento index. index has built successfully for 100k records, it took 10-13 mins for 1 store, but we had 10 store views.

but i have changed category and added new static block, monitoring when it will flow to ES. checking if it appends data or clean and rebuild.

keep you updated.

**Comment by nagrgkgc** [comment]
@afirlejczyk 

to confirm and close this ticket, magento index is working and pushing data for vsindex as well.
reindex works in delta mode.

will reopen this ticket is any other issue found with same scenario.

**Comment by afirlejczyk** [comment]
```
to confirm and close this ticket, magento index is working and pushing data for vsindex as well.
```
Yes, that was the purpose to use Magento native indexers ;)
