### ISSUE TITLE
giftcard_amounts

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/magento2-vsbridge-indexer#297]
For giftcard products, I have flagged a bunch of attributes including `Amount (giftcard_amounts)`
In ES, I see pretty much all attributes correctly serialized, apart from giftcard_amounts wich is nowhere to be found

![image](https://user-images.githubusercontent.com/8209966/84638084-ce076380-aef6-11ea-926e-559098f0c6e9.png)

Am I doing anything wrong?
Let me know if you need further info

**Comment by afirlejczyk** [comment]
1. Do you have selected this attribute to export? Do you export all attributes?
2. Is this an EAV attribute? It's not available in Demo Sample Data so you have to check yourself why you don't have this data exported.
