### ISSUE TITLE
cms_hierarchy

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/magento2-vsbridge-indexer#298]
Any way to have the cms hierarchy (other than page and block) indexed in ES?

**Comment by afirlejczyk** [comment]
Hi,

There is nothing like the cms hierarchy available in the Magento Community version.
You have to create custom extension an export necessary data form Magento Commerce/Enterprise version: https://docs.magento.com/user-guide/cms/page-hierarchy.html, or whatever you want to have in there.

There is nothing like that available in the mage2vuestorefront tool.
I would ask about more details VSF Core team about this cms_hierarchy.

**Comment by undefinederror** [comment]
ok gotcha. Thank you
