### ISSUE TITLE
indexer reset status

### ISSUE THREAD

**Issue by nagrgkgc** [DivanteLtd/magento2-vsbridge-indexer#300]
Hi Storefront team

in invalid or in progress indexer status, your message is

WARNING: Indexation can't be executed. Some indices has invalid status: Vsbridge Product Indexer. Please change indices status to VALID manually.

you can change this message to :

"php bin/magento indexer:reset"

OR

you can add below code to reset status "vsbridge:resetindex" >> VSbridge specific

di.xml: <type name="Magento\Framework\Console\CommandListInterface">
item name="reset" xsi:type="object">Divante\VsbridgeIndexerCore\Console\Command\ResetEsIndexCommand</item

Core/Console/Command:
[ResetEsIndexCommand.php.zip](https://github.com/DivanteLtd/magento2-vsbridge-indexer/files/4784612/ResetEsIndexCommand.php.zip)

Thank you

**Comment by afirlejczyk** [comment]
Changes were merged with:
https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/303
