### ISSUE TITLE
CMS page longer index

### ISSUE THREAD

**Issue by nagrgkgc** [DivanteLtd/magento2-vsbridge-indexer#307]
hi team,

**Observation**.

I have observed many times that CMS page index takes very long always in full index.

<img width="690" alt="Screen Shot 2020-06-28 at 12 26 42 PM" src="https://user-images.githubusercontent.com/53718686/85942533-e5a10c00-b93a-11ea-8fb0-94d8b7d9d693.png">

15-16 mins for some of 200-400 pages. is this expected or some joins causing this issue?

Thank you

**Comment by afirlejczyk** [comment]
I am not sure if joining is the problem.
Maybe processing content and switching store code can cause the problem.

Could you try to comment out this code here
https://github.com/DivanteLtd/magento2-vsbridge-indexer/blob/master/src/module-vsbridge-indexer-cms/Model/Indexer/DataProvider/CmsContentFilter.php

and check how long it takes to reindex than?

change function to this
```
public function filter(array $indexData, int $storeId, string $type)
    {
 
        return $indexData;
    }
```

I don't know what you have on your cms pages.. if you might have some products list/widgets it might take longer to process. 
It really might depends what content you have there. If you don't use all of this pages in VSF maybe it will be best to deactive this pages (only active CMS Pages are exported to ES)?
