### ISSUE TITLE
Secure VueStorefrontIndexer reindexing

### ISSUE THREAD

**Issue by jonathanribas** [DivanteLtd/magento2-vsbridge-indexer#308]
First of all, I'm not an Elasticsearch expert, maybe there are shortcuts with the API calls. I'm just trying to make things working better than it's actually.

Vsfbridge reindexing job is actually not checking Elasticsearch status neither it's queue thread on bulk operations before sending more operations to update your data.

1. Check your Elasticsearch status

`GET /_cat/health?format=json`

**Response**

`
{
    "epoch": "1594120992",
    "timestamp": "13:23:12",
    "cluster": "es-xxxxxxxx",
    "status": "green",
    "node.total": "6",
    "node.data": "3",
    "shards": "334",
    "pri": "167",
    "relo": "0",
    "init": "0",
    "unassign": "0",
    "pending_tasks": "0",
    "max_task_wait_time": "-",
    "active_shards_percent": "100.0%"
}
`

If it's green we can proceed otherwise we stop reindex job.

As you can see, this endpoint also provides us the pending tasks.

2. Get your master node

`GET /_cat/master?format=json`

**Response**

`[
  {
    "id": "xxxxxxx",
    "host": "10.21.30.47",
    "ip": "10.21.30.47",
    "node": "yyyyy"
  }
]`

3. Get your nodes thread pool statistics

`GET /_cat/thread_pool?format=json`

**Response**

`[
  {
    "node_name": "x-1",
    "name": "bulk",
    "active": "0",
    "queue": "0",
    "rejected": "0"
  },
  {
    "node_name": "x-2",
    "name": "bulk",
    "active": "0",
    "queue": "0",
    "rejected": "0"
  },
  {
    "node_name": "x-3",
    "name": "bulk",
    "active": "0",
    "queue": "0",
    "rejected": "0"
  },
  {
    "node_name": "x-4",
    "name": "bulk",
    "active": "0",
    "queue": "0",
    "rejected": "0"
  },
  {
    "node_name": "x-5",
    "name": "bulk",
    "active": "0",
    "queue": "0",
    "rejected": "0"
  },
  {
    "node_name": "x-6",
    "name": "bulk",
    "active": "0",
    "queue": "0",
    "rejected": "0"
  }
]`

Part the result to get your master one.

4. Get master node thread_pool bulk size

`GET _nodes/xxxxx/thread_pool` where `xxxxx` is your master node

Parse result to get the `bulk queue_size`.

If pending tasks + batch indexer size (VueStorefrontIndexer indices setting) are lower than max bulk queue size master node, it means we are healthy and we can proceed. 

As bulk operations are in a loop, we can implement an error log if load is too high.

**Comment by jonathanribas** [comment]
I've also found this [article](https://qbox.io/blog/maximize-guide-elasticsearch-indexing-performance-part-2) which suggest before launching a bulk operation to update` index.refresh_interval` to `-1`.  At the end of bulk operation, just enable it back.

If you have replicas, they also suggest to disable replication when running bulk operations, set it to `index.number_of_replicas: 0`.

**Comment by afirlejczyk** [comment]
Changes are available in master branch.
