### ISSUE TITLE
Indexing mulitple stores issue

### ISSUE THREAD

**Issue by chanwooro** [DivanteLtd/magento2-vsbridge-indexer#310]
Hi,

I am currently trying to achieve indexing multiple stores but it seems to be only indexing the first/default store but not other stores. I have created a new store that is bound to the same website as the default store one and then created a new store view that is pointing to the newly created store. 

![ss](https://user-images.githubusercontent.com/11813602/87263619-d791e480-c511-11ea-8f3e-91f912064fb5.jpg)

and then flushed magento 2 cache and then reindexed via bin/magento indexer:reindex

Could you help me or guide me if I am doing this wrong?

**Comment by afirlejczyk** [comment]
Hi,
You have to choose in the configuration which stores you want to reindex.
https://github.com/DivanteLtd/magento2-vsbridge-indexer/blob/master/docs/configuration.md
Stores → Configuration → Vuestorefront → Indexer → General settings → List of stores to reindex
