### ISSUE TITLE
Price and Special Price is not updating in ES

### ISSUE THREAD

**Issue by nitikeshd** [DivanteLtd/magento2-vsbridge-indexer#311]
Hi there,

Step to reproduce:

1. change the price and Special price of a simple and configurable product in the magento backend
2. Run Product Indexer
3. Price is not getting updated in the Elastic Search

Is there something which we are missing here? 

Sometimes back it was working as i checked it. However not sure why it is not working now. Is it a configuration which we need to make sure or a code issue?

NOTE:
Product indexer works fine
Product name is changing

**Comment by nitikeshd** [comment]
Any update on this one?
 @afirlejczyk

**Comment by afirlejczyk** [comment]
Hi,
All attributes are triggering an update in ES, a special price as well. I don't know why it doesn't work in your case. It might be connected with this bug  https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/273. Did you check if it might be the issue?

You can write how you configure the product - add a screen from magento backend. Which Magento version do you use? Do you have a multistore?
Right now I don't have to investigate it.

**Comment by nitikeshd** [comment]
thank you for your response @afirlejczyk ,  We are using multi store. magento version is 2.2.5. 
Tried with Update on Save but same result. Will it be possible to have a call and discuss?

**Comment by afirlejczyk** [comment]
This issue might be fixed with this: https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/273
