### ISSUE TITLE
Update By schedule add support for Magento Commerce

### ISSUE THREAD

**Issue by afirlejczyk** [DivanteLtd/magento2-vsbridge-indexer#32]
Mode "Update by Schedule" might not work correctly in Magento Commerce

**Comment by afirlejczyk** [comment]
Check if is working in full.

**Comment by jonathanribas** [comment]
Why do you think Update By Schedule won't work on Magento Commerce?

**Comment by afirlejczyk** [comment]
It probably works as excepted.
I just didn't have time to check it in March - that's the only reason I leave this issue open. ;)
