### ISSUE TITLE
Indexer reset command name overrides Magento indexer:reset command 

### ISSUE THREAD

**Issue by Vandeveon** [DivanteLtd/magento2-vsbridge-indexer#324]
Magento 2.3.3 Installation

Currently, Magento 2 indexer:reset command is not showing up during bin/magento execution, from some digging in code found that one of the vsbridge commands include the same name as indexer:reset command in di.xml and this prevents it from displaying the Magento command

File location
`src/module-vsbridge-indexer-core/etc/di.xml`

temporary solution change command name to something else
```
<item name="reset > reset_vsbridge" xsi:type="object">Divante\VsbridgeIndexerCore\Console\Command\ResetEsIndexCommand</item>
```

**Comment by nagrgkgc** [comment]
@Vandeveon 
this can be renamed.

renaming would work? if yes, we can commit change for this

**Comment by Vandeveon** [comment]
@nagrgkgc 
Yes after renaming indexer:reset command appeared again

**Comment by afirlejczyk** [comment]
Yes, we shouldn't override magento native commands. I will update the name.
