### ISSUE TITLE
ElasticSearch healthCheck at checkout

### ISSUE THREAD

**Issue by nagrgkgc** [DivanteLtd/magento2-vsbridge-indexer#325]
Hi All

Do you have any reason that VSINDEX Elasticsearch being called at checkout?
since this is admin module , it should be used at admin only and not frontend.

have you used any dependancy in frontend ?

please explain.

**Comment by afirlejczyk** [comment]
We are using magento 2 native indexers. Indexers are trigger on varient events: product save, category save, etc - you have take a look.

`vsbridge_product_indexer` index also depends from `catalog_product_price` and `cataloginventory_stock`

**Comment by nagrgkgc** [comment]
@afirlejczyk 

I understand but native does many things which we should not using in VSINDEX, 
people use storefront for admin data push and they would whitelist admin IP only.

i think this indexing and using magento native should be seggreagated totaly.

**Comment by nagrgkgc** [comment]
@afirlejczyk 

why checkout or frontend would access elasticsearch because price or category save is for admin should reflect in admin.
but why frontend changes would push data to elasticsearch?

logically this is not right.
