### ISSUE TITLE
Tax Indexer: Customer and Product tax class ids are registered wrongly

### ISSUE THREAD

**Issue by mamsincl** [DivanteLtd/magento2-vsbridge-indexer#353]
https://mysite.local.com/vue_storefront_magento/taxrule/_search?pretty
![image](https://user-images.githubusercontent.com/17334804/97894115-0be01980-1d2a-11eb-9e15-4810caff0287.png)

M2 backend:
![image](https://user-images.githubusercontent.com/17334804/97897667-b78b6880-1d2e-11eb-8f96-ce181be46a34.png)

As you see indexer nicely picking up every information except Customer and Product Tax classes.
The related indexer part it falling back to https://github.com/DivanteLtd/magento2-vsbridge-indexer/blob/main/src/module-vsbridge-indexer-tax/ResourceModel/TaxClasses.php#L39, and according to _fetchAssoc($select)_:

> Fetches all SQL result rows as an associative array.
>
> The first column is the key, the entire row array is the value.
> You should construct the query to be sure that the first column contains unique values,
> or else rows with duplicate values in the first column will overwrite previous data.

Running the row query directly on DB results in 42 rows, but during debugging (since the limitation of the _fetchAssoc_) only can see 4 records.

**Comment by afirlejczyk** [comment]
By looking how data meant to be processed in `../DataProvider/TaxClasses.php`, `fetchAll` should be used to get records instead a `fetchAssoc`. I will make  a fix.
