### ISSUE TITLE
Index not found exception after reindex

### ISSUE THREAD

**Issue by Tjitse-E** [DivanteLtd/magento2-vsbridge-indexer#41]
Hi,

I'm testing this module, to see if it is ready to replace mage2vuestorefront, which we are currently using. But after installing the module and running the Magento indexers, i'm having troubles with linking the elastic indexes generated by the Magento 2 indexer with the VueStorefront API.

Error when searching for data via the API with https://my-vue-storefront.nl/api/catalog/vue_storefront_catalog/_search
```
{  
   "error":{  
      "root_cause":[  
         {  
            "type":"index_not_found_exception",
            "reason":"no such index",
            "resource.type":"index_or_alias",
            "resource.id":"vue_storefront_catalog",
            "index_uuid":"_na_",
            "index":"vue_storefront_catalog"
         }
      ],
      "type":"index_not_found_exception",
      "reason":"no such index",
      "resource.type":"index_or_alias",
      "resource.id":"vue_storefront_catalog",
      "index_uuid":"_na_",
      "index":"vue_storefront_catalog"
   },
   "status":404
}
```

### Settings
I've setup the index name prefix like this:
![ Magento Admin 2019-04-19 16-00-09](https://user-images.githubusercontent.com/14849044/56427459-3c816f00-62bc-11e9-92d1-3c2feaeee700.png)

The indexes are generated with elastic:
![vue-storefront-api (ssh) 2019-04-19 16-02-48](https://user-images.githubusercontent.com/14849044/56427557-a13cc980-62bc-11e9-9eb6-ae72182084e8.png)

My vue-storefront and vue-storefront-api settings:
![vue-storefront (ssh) 2019-04-19 16-00-48](https://user-images.githubusercontent.com/14849044/56427510-70f52b00-62bc-11e9-8733-dc8219dd99ab.png)

![vue-storefront-api (ssh) 2019-04-19 16-02-08](https://user-images.githubusercontent.com/14849044/56427523-836f6480-62bc-11e9-9dd4-d0097190a936.png)

Are these settings allright? Or have I misinterpreted the docs?

**Comment by pkarw** [comment]
@afirlejczyk could You please advise us in here?

**Comment by afirlejczyk** [comment]
Hi @Tjitse-E 
You have to update indices in VSF configuration.
`vue_storefront_catalog` -> is an index alias. This module is not using aliases (yet), it only operates on index name.

For every store view we have a new index in Elastic with a name like:
[INDEX PREFIX]_[STORE ID], so base on your settings we will have indices with names:
'vue_storefront_catalog_1', 'vue_storefront_catalog_2', etc. 

So you have to replace `vue_storefront_catalog` in configuration with 
`vue_storefront_catalog_1`  (in vsf and vsf-api)

**Comment by Tjitse-E** [comment]
Thanks for the clarification @afirlejczyk! This seems to work correctly.
