### ISSUE TITLE
Installation errors on magento 2.3.1

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/magento2-vsbridge-indexer#43]
Hi, have a good day!

I try to install to magento 2.3.1 and see errors related to ES version:

![2019-05-07_11-01-05](https://user-images.githubusercontent.com/414067/57278483-9d2fea80-70b7-11e9-92df-99fa0a13ac62.png)

**Comment by dimasch** [comment]
I check with `*` and reindex worked correctly on `m2.3.1`

**Comment by afirlejczyk** [comment]
We have to probably change requirement to
`"elasticsearch/elasticsearch": ">=5.1"`

**Comment by madonzy** [comment]
I just updated to Magento 2.3.1 and can't reproduce that issue. Tried with dev-master and dev-develop, the process goes smoothly.

<img width="929" alt="Screenshot 2019-05-09 at 14 42 36" src="https://user-images.githubusercontent.com/5281020/57454989-6221e880-726a-11e9-87ff-fbd22c9d98d3.png">

<img width="1006" alt="Screenshot 2019-05-09 at 14 40 57" src="https://user-images.githubusercontent.com/5281020/57455013-74038b80-726a-11e9-9cff-e852aed56c93.png">
