### ISSUE TITLE
Backward compatibility with 2.2.x

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/magento2-vsbridge-indexer#53]
See errors on Magento `2.2.5`, and ES index not created.

![2019-05-30_12-24-30](https://user-images.githubusercontent.com/414067/58619695-73449f00-82d6-11e9-9f62-99f894814b39.png)

Related commit
https://github.com/DivanteLtd/magento2-vsbridge-indexer/commit/cdebbbc4b79fed2d1e872ab37f3ba6ffe2b07d96

**Comment by dennisotugo** [comment]
+1

**Comment by dennisotugo** [comment]
@afirlejczyk any suggestion on working around this?

**Comment by afirlejczyk** [comment]
@dennisotugo you can check changes on the branch
`feature/compatibility-with-magento-2-5`
I plan to merge changes to develop soon.

**Comment by afirlejczyk** [comment]
Fixed with https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/110
