### ISSUE TITLE
Content types differ from mage2vuestorefront

### ISSUE THREAD

**Issue by DaanKouters** [DivanteLtd/magento2-vsbridge-indexer#58]
Firstly, really great work on this, indexing is really quick.

I noticed that the content types of attribute options differ from the content type provided by mage2vs. This is not an issue per se, but their is a difference i think we should discuss about.

Magento Attribute boolean types are 'true' or 'false', and importing data via mage2vs these are '1' or '0'.
Multiselect attributes with multiple options for a products are imported as arrays, that's great, but the option_ids in this array should be integers but are now strings.
Attribute options that are not filled in Magento are imported as NULL value, while in mage2vs these options are stripped from the dataset

**Comment by afirlejczyk** [comment]
```
Multiselect attributes with multiple options for a products are imported as arrays, that's great, but the option_ids in this array should be integers but are now strings.
```

That I will check.

@pkarw what do you think about other two points ?
```
Magento Attribute boolean types are 'true' or 'false', and importing data via mage2vs these are '1' or '0'.
Attribute options that are not filled in Magento are imported as NULL value, while in mage2vs these options are stripped from the dataset
```

**Comment by pkarw** [comment]
Hey! Im not siren if it makes any difference. I mean - we should check if the values are accepted by the default elastic scheme. If so - for JS logic it makes no difference if we have 0/1/true/false

**Comment by afirlejczyk** [comment]
@pkarw what do you mean by "default elastic scheme"? 
In indexer, mapping is created a dynamicly base on attribute type.
We like "calculated" type base on attribute metadata. 
So it different a little than mapping created by vsf-api/mage2vuestorefront.
But for now, I don't see any problem with that..
Important fields, has the same mapping like: slug, sku, url_path, url_key, etc.

In mage2vsf -> we have schema for some attributes/fields, but for the rest (custom attributes) mapping is created dynamically by ES. 

we can always change the mapping for boolean attributes to 0/1 -> for me it doesn't make any difference right now. Maybe for some real use cases, it might be better, I don't have an opinion on that.

**Comment by afirlejczyk** [comment]
@DaanKouters 
```
Multiselect attributes with multiple options for a products are imported as arrays, that's great, but the option_ids in this array should be integers but are now strings.
```
Done, multiselect values will be now exported as integers as they should.

**Comment by DaanKouters** [comment]
> @DaanKouters
> 
> ```
> Multiselect attributes with multiple options for a products are imported as arrays, that's great, but the option_ids in this array should be integers but are now strings.
> ```
> 
> Done, multiselect values will be now exported as integers as they should.

Great, thank you.

**Comment by afirlejczyk** [comment]
@DaanKouters  @pkarw I think I can close this one ?
