### ISSUE TITLE
Required Elastic search version

### ISSUE THREAD

**Issue by allrude** [DivanteLtd/magento2-vsbridge-indexer#60]
this version won't install with Magento 2.3.1 it has a problem with the Magento 2.3.1 ES 6.7.1 version.

**Comment by rain2o** [comment]
I just tried to install this to test it out and ran into this issue as well. Any update on this?
Using Magento 2.3.1

**Comment by pkarw** [comment]
Vue Storefront is not supporting ES 6.x yet; please do install 5.x in order to run the indexer

**Comment by afirlejczyk** [comment]
I can change the requirement for elastisearch library client (https://github.com/elastic/elasticsearch-php),
The module should propably work wilth elasticsearch library 6.*, but you still need ES in version 5.*

**Comment by afirlejczyk** [comment]
It is fixed on develop branch.
