### ISSUE TITLE
Unable to bin/magento setup:install with plugin

### ISSUE THREAD

**Issue by razza12** [DivanteLtd/magento2-vsbridge-indexer#65]
Hi,

We are unable to run the magento installer if the plugin has been added by composer. It gives the following error 
```
[Progress: 481 / 877]
Module 'Magento_CatalogSearch':
In PatchApplier.php line 167:
No alive nodes found in your cluster
```

Once the plugin is disabled in app/etc/config.php then the install process will finish.

**Comment by afirlejczyk** [comment]
This Error appears when there is no connection with elasticsearch on
`127.0.0.1:9200` (default configuration for es)

But it was fixed on develop branch, and by default exporting data to ES is disable now.
https://github.com/DivanteLtd/magento2-vsbridge-indexer#configuration
