### ISSUE TITLE
Magento 2 catalog promotion unavailable on front-end

### ISSUE THREAD

**Issue by MarekBo** [DivanteLtd/magento2-vsbridge-indexer#71]
Indexer is awesome, thank you for it!

But I found special case about catalog promotion. 

Steps to reproduce:
1. In Magento 2 I have product with price $150
![m2_regular_price](https://user-images.githubusercontent.com/32968075/60008642-b5ae9100-9674-11e9-8278-6a24d7c010d7.png)

I see that product and price in VSF too
![vsf_regular_price](https://user-images.githubusercontent.com/32968075/60008698-cf4fd880-9674-11e9-95d9-f2fc4f972fb8.png)

2. Then I set special price for product (advance price) and I see correct result in M2 front-end
![m2_sp_admin](https://user-images.githubusercontent.com/32968075/60009293-eba04500-9675-11e9-830b-6b9d52f311aa.png)
![m2_sp_front](https://user-images.githubusercontent.com/32968075/60009342-ff4bab80-9675-11e9-99da-a09d4a9abda8.png)

and in VSF
![vsf_sp](https://user-images.githubusercontent.com/32968075/60009446-315d0d80-9676-11e9-9fa8-cee3a25c3b5a.png)

3. Afterwards I set Catalog Price Role (50% for all products). I see correct price in M2
![m2_catalog_pr](https://user-images.githubusercontent.com/32968075/60009785-bfd18f00-9676-11e9-81c1-2a79ae2bbeb6.png)

but in VSF I still see previous price
![vsf_catalog_pr](https://user-images.githubusercontent.com/32968075/60009849-e42d6b80-9676-11e9-9bf4-ff2a429ec4fd.png)

When I check Elasticsearch I see correct "final_price"
![es_sp](https://user-images.githubusercontent.com/32968075/60010603-61a5ab80-9678-11e9-8f8c-e128d1127da3.png)

but VSF get price from "special_price" not from "final_price"

**Comment by pkarw** [comment]
Thanks Marek! We need to use the `final_price` in the frontend to calculate the product price in this case!

**Comment by afirlejczyk** [comment]
@pkarw @MarekBo I think we can close this one?

**Comment by pkarw** [comment]
Yes, I belive so :) Thanks!
