### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by rain2o** [DivanteLtd/magento2-vsbridge-indexer#76]
This is a question, not an issue. Is there a planned release schedule for this module? I see there has been only one release so far, and multiple updates to the develop branch since then. I would like to use some of these updates but would rather not use `dev-develop` to avoid unwanted updates.

**Comment by afirlejczyk** [comment]
Hi @rain2o .
No there is no release schedule.
I will probably merge all changes to master soon (at the end of this week or at the beginning of the next week). So the new version should be available soon. I will let you know.

**Comment by rain2o** [comment]
Thanks @afirlejczyk . Would it be possible to include #68 when you do this? I see it has been approved but not merged. We are waiting for that to be included before we can start using this tool.

**Comment by afirlejczyk** [comment]
Yes, I merged it to develop yesterday. I plan to merge all changes to master tomorrow.
