### ISSUE TITLE
Add support for `configurable_options.label`

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/magento2-vsbridge-indexer#81]
Hi there! In `mage2vuestorefront` we're setting up the `product.configurable_options.label` by extrapolating the `value_index` to exact attribute label

https://github.com/DivanteLtd/mage2vuestorefront/blob/c71788e1c918225685344657f9d6ca0b2417d801/src/adapters/magento/product.js#L486

Can we apply this to `magento-2-vsbridge` indexer as well?

**Comment by afirlejczyk** [comment]
We have a label for configurable_options, but we don't have a label for configurable_options.values. 
I will add this.
