### ISSUE TITLE
Add `parent_sku` field

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/magento2-vsbridge-indexer#84]
Related to: https://github.com/DivanteLtd/vue-storefront/pull/3090

It will be great if we can add the `parent_products` to the products (`simple` one's) to mark up the parent products (it's probably `n:m` relationship, correct?). Without this relationship it's very very hard to find the parent product when you get the simple one

Or maybe there is another way?

**Comment by Hypo386** [comment]
Hi

I will take it

**Comment by afirlejczyk** [comment]
@pkarw It's a requirment for VSF, or this should be an optional?

**Comment by pkarw** [comment]
This is na optional feature as far as I know I mean it’s not used in vsf core yet

**Comment by afirlejczyk** [comment]
@pkarw Thanks.
Will you need this at all for VSF?

It looks like in the latest version on VSF we don't really need to export variants for configurable products.. (as separated documents). 
I'm on the right track ? Or some VSF configurations require simple variants in ES and some doesn't ?

**Comment by pkarw** [comment]
@afirlejczyk we still need it - we didn't change anything related to configurable logick

**Comment by Hypo386** [comment]
Added parent_sku field.

e.g.

"parent_sku":["MH01","MH02"]

Added new parent_data data provider Divante\VsbridgeIndexerCatalog\Model\Indexer\DataProvider\Product\ParentData for indices.

https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/152
