### ISSUE TITLE
created_at field missing from products

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/magento2-vsbridge-indexer#87]
The `mage2vuestorefront` is importing the `created_at` field for products, but the indexer is not. Is there a reason for this?

My colleague created a feature that adds a "New product" badge to products added in the last n days. I couldn't understand how she had been able to get the field to elasticsearch, until I realized she was using mage2vuestorefront and I was using the indexer.

**Comment by afirlejczyk** [comment]
No, it was just not used in VSF core, so that's why it is omitted.

**Comment by afirlejczyk** [comment]
@juho-jaakkola you are welcome to make a PR with requested changes.

**Comment by juho-jaakkola** [comment]
I ended up using two custom attributes (`new_from_date` and `new_to_date`) instead. So can be closed, and reopened if someone else runs into the same need.
