### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by shabbir-bharmal** [DivanteLtd/magento2-vsbridge-indexer#90]
I have setup the vue-storefront/vue-storefront-api and magento2 server in the same instance in google cloud server. I have followed the steps written in the documentation for installing indexer in magento. I'm running vue-storefront-api and magento server in the docker container but still I'm always getting the "No alive nodes found in your cluster" error. Can anyone help me out here?
![Screen Shot 2019-08-02 at 7 13 02 PM](https://user-images.githubusercontent.com/29979167/62374455-a36c2080-b559-11e9-9302-2fbd394ce3af.png)

**Comment by Hypo386** [comment]
Hi,

it means that there is no clear connection from Magento to container with elasticsearch.

When Magento is containerized it has to be in same docker network together with vue-storefront-api containers.

`docker network inspect vue-storefront-api_default` can help to determine networks

Be sure there is proper configuration in Magent owhich uses containers

![image](https://user-images.githubusercontent.com/4815371/69730390-3f80ef80-1128-11ea-99cc-866b01f6fcbd.png)
